# Generated by Django 3.2.6 on 2022-04-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0005_fcn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCN',
        ),
    ]
